### ISSUE TITLE
Example at https://rdrr.io/github/nimble-dev/nimbleEcology/man/dHMM.html throws an error

### ISSUE THREAD

**Issue by DrMattG** [nimble-dev/nimbleEcology#10]
Hei! The example at https://rdrr.io/github/nimble-dev/nimbleEcology/man/dHMM.html throws an error: "Error in genVarInfo3() : 
  dimensions specified are smaller than model specification for variable 'probObs'"

Cheers
Matt

```
len <- 5 # length of dataset
dat <- c(1,2,1,1,2) # A vector of observations
init <- c(0.4, 0.2, 0.4) # A vector of initial state probabilities
probObs <- t(array( # A matrix of observation probabilities
  c(1, 0,
    0, 1,
    0.2, 0.8), c(2, 3)))
probTrans <- t(array( # A matrix of transition probabilities
  c(0.6, 0.3, 0.1,
    0, 0.7, 0.3,
    0, 0, 1), c(3,3)))

# Define code for a nimbleModel
nc <- nimbleCode({
  x[1:5] ~ dHMM(init[1:3], probObs = probObs[1:2,1:3],
                probTrans = probTrans[1:3, 1:3], len = 5)
  
  for (i in 1:3) {
    init[i] ~ dunif(0,1)
    
    for (j in 1:3) {
      probTrans[i,j] ~ dunif(0,1)
    }
    
    probObs[i, 1] ~ dunif(0,1)
    probObs[i, 2] <- 1 - probObs[1,i]
  }
})

# Build the model
HMM_model <- nimbleModel(nc,
                         data = list(x = dat),
                         inits = list(init = init,
                                      probObs = probObs,
                                      probTrans = probTrans))
#Error here
#defining model...
#Error in genVarInfo3() : 
#  dimensions specified are smaller than model specification for variable 'probObs'

# Calculate log probability of data from the model
HMM_model$calculate()
# Use the model for a variety of other purposes...
```

**Comment by danielturek** [comment]
Matt, it looks like there's a minor typo or two in the example code.  Our
apologies!  Try the modified code below, it should work for you now.  I
indicated the modified lines with the comment "DT".

Also included, I commented out the prior for the "init[i]" nodes, since
as-previously-written those would be independently sampled, and violate the
sum-to-one restraint.  If one truly wants a prior on the "init[i]" values,
then a multivariate Dirichlet prior on the "init[1:3]" node would be
appropriate.

Let us know if you run into any other issues.

Daniel



library(nimble)
library(nimbleEcology)

len <- 5 # length of dataset
dat <- c(1,2,1,1,2) # A vector of observations
init <- c(0.4, 0.2, 0.4) # A vector of initial state probabilities

probObs <- t(array( # A matrix of observation probabilities
    c(1, 0,
      0, 1,
      0.2, 0.8), c(2, 3)))

probTrans <- t(array( # A matrix of transition probabilities
    c(0.6, 0.3, 0.1,
      0, 0.7, 0.3,
      0, 0, 1), c(3,3)))

# Define code for a nimbleModel
nc <- nimbleCode({
    x[1:5] ~ dHMM(init[1:3], probObs = probObs[1:3,1:2],   ## DT: modified
indices
                  probTrans = probTrans[1:3, 1:3], len = 5)
    for (i in 1:3) {
        ##init[i] ~ dunif(0,1)   ## DT: commented line
        for (j in 1:3) {
            probTrans[i,j] ~ dunif(0,1)
        }
        probObs[i, 1] ~ dunif(0,1)
        probObs[i, 2] <- 1 - probObs[i, 1]   ## DT: modified indices
    }
})

# Build the model
HMM_model <- nimbleModel(nc,
                         data = list(x = dat),
                         inits = list(init = init,
                             probObs = probObs,
                             probTrans = probTrans))

# Calculate log probability of data from the model
HMM_model$calculate()   ## -5.872438

**Comment by dochvam** [comment]
Hi Matt, thanks for bringing this issue up. The example has been fixed per Daniel's helpful suggestions in the branch typo_fixes. It will be submitted to CRAN today as nimbleEcology 0.2.1 and merged into master.
